### ISSUE TITLE
Battery recipes incorrect

### ISSUE THREAD

**Issue by netmc** [NoMansSkyAssistant/General#1]
The recipe listed for the advanced ion battery is actually the recipe for the regular ion battery.  The regular battery takes cobalt and ferrite, while the advanced battery uses ionized cobalt and pure ferrite.

**Comment by Khaoz-Topsy** [comment]
Hey! Thank you for letting me know! I have made the change, and the app will get the fix on next release, hopefully by tomorrow

**Comment by Khaoz-Topsy** [comment]
Recipe has been updated and fixed in version 1.3.11 😁 Which is live 🎉
