### ISSUE TITLE
Solar/Battery Calculator not opening

### ISSUE THREAD

**Issue by albertdick** [NoMansSkyAssistant/General#10]
Just show a grey screen.

IPhone 7.
iOS 14.0.1.
App version: 1.59.0

![image](https://user-images.githubusercontent.com/8559840/96830208-6cf61c00-1411-11eb-897f-0f3b16d745f3.png)

**Comment by Khaoz-Topsy** [comment]
Thank you for opening an issue @albertdick, I am happy to say that I found the bug (It was thanks to the new null safety features coming to Flutter) the error message was "null check operator used on a null value" Which is definitely a weird one. The Solar Battery Calculator should be working again from Release 1.60. The update is already live on Android and should be available on iOS in a few hours. I am guessing it will be live on iOS by 10PM GMT+2 🤔

I will close this once I have tested on iOS
