### ISSUE TITLE
Recipes without title and description in Brazilian Portuguese

### ISSUE THREAD

**Issue by albertdick** [NoMansSkyAssistant/General#12]
In Brazilian Portuguese language, the recipes titles and their descriptions are empty.

![image](https://user-images.githubusercontent.com/8559840/131583672-86949153-40f2-4d6a-b118-aa46b2bf123c.png)

![image](https://user-images.githubusercontent.com/8559840/131583691-f993c4f0-4ff9-466f-8407-3e58bee649f8.png)

App version: 1.89.2
iPhone 7. iOS: 14.7.1

Note: This has been going on for some previous versions (not just the latest version).

**Comment by albertdick** [comment]
I sent an email to support.

**Comment by Khaoz-Topsy** [comment]
This should be double fixed now 😂

1. Hello Games assigned names to those items 
2. I have made the items display "Unknown" in the current language when the name is empty. (Future proofed the fix) 🎉
