### ISSUE TITLE
Android back button

### ISSUE THREAD

**Issue by Kycko** [NoMansSkyAssistant/General#2]
For now when I'm pressing device's back button your application closes... Please change this, it must open previous page like other Android apps 🤔

**Comment by Khaoz-Topsy** [comment]
Thank you for creating the issue! It is a bug I caused when trying to optimize the app 😅. I will let you know when I fix it 😁

**Comment by Khaoz-Topsy** [comment]
The navigation has been fixed in the latest version 😁
