### ISSUE TITLE
Blueprint changes

### ISSUE THREAD

**Issue by waldo3000** [NoMansSkyAssistant/General#4]
The app suggests making cobalt mirror from ionised cobalt but the game actually makes cobalt from ionised cobalt.  Not sure, but this may have changed in the Synthesis release.

using version 1.14.0

**Comment by Khaoz-Topsy** [comment]
Thanks for opening an issue! I will check it out 😋

**Comment by Khaoz-Topsy** [comment]
Sorry for taking so long to respond, while checking in game I got a bit distracted 😅

Cobalt Mirror requires 50 Ionised Cobalt to be crafted.
You can refine Ionised Cobalt into Cobalt.

So everything looks right if I understand the issue you opened, let me know if I misunderstood 🙂

**Comment by waldo3000** [comment]
I'm sorry, I was confusing crafting blueprints and refiner recipes.  In fact, I had assumed the formulas were always the same for crafting and refining.  I guess I learned something new !

Thanks.
