### ISSUE TITLE
all screens blank

### ISSUE THREAD

**Issue by ukmerlin** [NoMansSkyAssistant/General#6]
All game pages are blank only menu and settings pages show anything

**Comment by Khaoz-Topsy** [comment]
Sorry to hear that 😓. can you please give me your Android version and your phone model please?
Since you can navigate to settings, can you tell me what version you are on? (It's listed right at the bottom of the menu)

**Comment by Khaoz-Topsy** [comment]
A few people have reported this issue, it seems that clearing the App Data resolves the issue 🙂

**Comment by Khaoz-Topsy** [comment]
I haven't had any reports of this still being an issue, are you still having this issue @ukmerlin ?
