### ISSUE TITLE
Please support iPad screens

### ISSUE THREAD

**Issue by Tenzian** [NoMansSkyAssistant/General#7]
The app doesn't support iPad screen resolutions or landscape orientation:

![IMG_0002](https://user-images.githubusercontent.com/13963952/78425769-649fe480-766b-11ea-8ac4-9d06150d6a32.png)

![IMG_0003](https://user-images.githubusercontent.com/13963952/78428059-163f1580-766c-11ea-8817-f32d2e923f4d.png)

**Comment by Khaoz-Topsy** [comment]
Oh wow, that sucks 😅. I will look into it

**Comment by Khaoz-Topsy** [comment]
I think I have a solution, the next update should make the App take up all the space 😁

**Comment by Khaoz-Topsy** [comment]
@Tenzian The update is live! please let me know if it worked or failed 😅

**Comment by Tenzian** [comment]
Yes, that's fixed the resolution issue now. Thanks!
